// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ2RzdCvYZhRyS9mKSkuU-lxjFOcxJa0k',
    appId: '1:901986478731:web:d3be49576183ea715a428e',
    messagingSenderId: '901986478731',
    projectId: 'fir-flutter-2-d8f66',
    authDomain: 'fir-flutter-2-d8f66.firebaseapp.com',
    storageBucket: 'fir-flutter-2-d8f66.firebasestorage.app',
    measurementId: 'G-BFC3YZ77S0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8iQJ-3bxbDohSgneox3mj2Zt3ctGFigI',
    appId: '1:901986478731:android:8047d291499f5de75a428e',
    messagingSenderId: '901986478731',
    projectId: 'fir-flutter-2-d8f66',
    storageBucket: 'fir-flutter-2-d8f66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDevRVaaT3zPPKbQ6j52gMHyipLVuor9wU',
    appId: '1:901986478731:ios:d85fd4ee8a6a78a85a428e',
    messagingSenderId: '901986478731',
    projectId: 'fir-flutter-2-d8f66',
    storageBucket: 'fir-flutter-2-d8f66.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDevRVaaT3zPPKbQ6j52gMHyipLVuor9wU',
    appId: '1:901986478731:ios:d85fd4ee8a6a78a85a428e',
    messagingSenderId: '901986478731',
    projectId: 'fir-flutter-2-d8f66',
    storageBucket: 'fir-flutter-2-d8f66.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ2RzdCvYZhRyS9mKSkuU-lxjFOcxJa0k',
    appId: '1:901986478731:web:da292d97541d126c5a428e',
    messagingSenderId: '901986478731',
    projectId: 'fir-flutter-2-d8f66',
    authDomain: 'fir-flutter-2-d8f66.firebaseapp.com',
    storageBucket: 'fir-flutter-2-d8f66.firebasestorage.app',
    measurementId: 'G-ZLJ5ZJM9N8',
  );

}